name: helpfeed2
description: Food Donation Application


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_core: ^2.3.0
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.5
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  dropdown_button2: ^1.9.1
  url_launcher: ^6.1.6
  file_picker: ^5.2.3
  google_maps_flutter: ^2.2.1
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.4
  google_sign_in: ^5.4.2
  persistent_bottom_nav_bar: any
  shared_preferences: ^2.0.15
  path: ^1.8.1
  flutter_easyloading: ^3.0.5
  geolocator: ^9.0.2
  overlay_support: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/